docs(getting-started): add ref to run-as-daemon
daeuniverse/dae pull request #147
Opened 2023-06-17 02:32 UTC by yqlbu

### Background

Add an entry point to direct users to `run-as-daemon.md`.

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOG
- [x] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full changelog

- docs(getting-started): add ref to run-as-daemon

### Issue reference

NA

2023-06-17 02:50 UTC, mzz2017 requested changes

2023-06-17 02:50 UTC, mzz2017 commented on docs/getting-started/README.md
> +## Run as daemon
Install by manual

2023-06-17 02:50 UTC, mzz2017 commented on docs/getting-started/README.md
> +dae can run as a daemon (systemd) service. See [run-as-daemon](run-as-daemon.md)
Out of date statement.
这不代表同层级下的其他方式不能 run as a deamon

2023-06-17 03:31 UTC, yqlbu commented on docs/getting-started/README.md
> +dae can run as a daemon (systemd) service. See [run-as-daemon](run-as-daemon.md)
Resolved.

2023-06-24 13:09 UTC, mzz2017 commented
LGTM

2023-06-24 13:09 UTC, mzz2017 approved these changes

2023-06-24 13:10 UTC, merged