feat: allow group override global node connectivity check
daeuniverse/dae pull request #623
Opened 2024-09-07 02:33 UTC by KagurazakaNyaa

### Background

此Pull Request允许group配置覆盖global配置中的节点联通性检查以支持更加灵活的场景

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [x] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full Changelogs

- 允许group段中的配置覆盖global的节点联通性检查配置
- 当group中未定义这些新的配置时，行为应当和之前完全一致
- 当group中存在这些新配置时，所有此group的dialer将会被克隆并修改联通性检查配置

### Issue Reference

Closes #619 

### Test Result

2024-09-07 04:30 UTC, mzz2017 requested changes

2024-09-07 04:30 UTC, mzz2017 commented on control/control_plane.go
> +				newDialer := d.Clone()
newDialer 没有被上述 deferFuncs = append(deferFuncs, dialerSet.Close) 处理到，需要手动使用 deferFuncs Close

2024-09-07 04:30 UTC, mzz2017 commented on control/control_plane.go
> +			newDialerSet := make([]*dialer.Dialer, 0)
语义差异，应当使用 newDialers，因为 DialerSet 是一个 struct

2024-09-07 04:30 UTC, mzz2017 commented on example.dae
> +        tcp_check_url: https://gstatic.com/generate_204
示例用法默认注释，推荐用法取消注释
```suggestion
        #tcp_check_url: https://gstatic.com/generate_204
```

2024-09-07 04:30 UTC, mzz2017 commented on example.dae
> +        #tcp_check_http_method: GET
example.dae 包含所有选项，建议将其他选项也加入进来。

2024-09-07 04:30 UTC, mzz2017 commented on control/control_plane.go
> +		option := dialer.GlobalOption{
建议将 GlobalOption 抽出为 NewGlobalOption，这样可以两处共用，降低未来修改多处代码漏改的概率

2024-09-07 04:31 UTC, mzz2017 commented
非常感谢你的贡献，代码质量看起来很不错

2024-09-07 09:54 UTC, KagurazakaNyaa commented
@mzz2017 上述提及的代码均已按建议修改，请再次review

2024-09-08 05:36 UTC, mzz2017 approved these changes
LGTM!

2024-09-08 09:28 UTC, mzz2017 commented
等待第三方测试后合入

2024-09-08 14:10 UTC, mzz2017 commented
测试一切正常，能正常工作

2024-09-08 14:12 UTC, mzz2017 approved these changes

2024-09-08 14:13 UTC, merged

2024-09-12 04:28 UTC, QiuSimons commented
@mzz2017 @KagurazakaNyaa 应用这个pr后编译基于此版本dae的daed，会导致daed更新订阅出错，无法获取到节点
报错如下
https://pastebin.com/RMCGjJad

2024-09-12 05:35 UTC, KagurazakaNyaa commented
> @mzz2017 @KagurazakaNyaa 应用这个pr后编译基于此版本dae的daed，会导致daed更新订阅出错，无法获取到节点 报错如下 https://pastebin.com/RMCGjJad

看了一下报错在 https://github.com/KagurazakaNyaa/dae/blob/d8fad755979e87fdb448eead497a650a18a23cf1/component/outbound/dialer/dialer.go#L101 似乎是打日志的时候引用了空指针
@mzz2017 请确认一下`d.Property().Name`dialer有这个属性吗，我好像没有找到，也许不应该使用这个字段来在日志中区分dialer？

2024-09-12 05:42 UTC, mzz2017 commented
@KagurazakaNyaa 应该是 daed 在 new dialer 的时候没有传入 property，而是传的空指针导致的，要改一下 dae-wing

2024-09-20 15:47 UTC, wanlce commented
@mzz2017 
daed 这边报错是因为 option.Log 为 nil
https://github.com/daeuniverse/dae/blob/cec5e71d4e99b3a359a88d05317f18e18463b9c7/component/outbound/dialer/dialer.go#L101

2024-09-20 15:53 UTC, mzz2017 commented
@wanlce 可否帮忙修一下？